/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 
 */
export interface BisAddress {
    /**
     * Nolla tarkoittaa yhteistä, yksi Patentti- ja rekisterihallitusta, kaksi Verohallintoa ja kolme yritys- ja yhteisötietojärjestelmää
     */
    source?: number;

    /**
     * Yksi tarkoittaa nykyistä versiota ja &gt;1 historiallisia osoitteita
     */
    version: number;

    /**
     * Rekisteröintipäivämäärä
     */
    registrationDate: Date;

    /**
     * Rekisteröinnin loppupäivämäärä
     */
    endDate?: Date;

    /**
     * c/o-osoite
     */
    careOf?: string;

    /**
     * Katuosoite
     */
    street?: string;

    /**
     * Postinumero
     */
    postCode?: string;

    /**
     * Postitoimipaikka
     */
    city?: string;

    /**
     * Kaksikirjaiminen kielikoodi
     */
    language?: string;

    /**
     * Osoitteen laji, käyntiosoite 1 , postiosoite 2
     */
    type: number;

    /**
     * Kaksikirjaiminen maakoodi
     */
    country?: string;

}
