/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 
 */
export interface BisCompanyRegisteredEntry {
    /**
     * Merkinnän kuvaus
     */
    description: string;

    /**
     * Nolla tarkoittaa yhteisiä merkintöjä, yksi ”Rekisteröimätön” ja kaksi ”Rekisteröity”
     */
    status: number;

    /**
     * Rekisteröintipäivämäärä
     */
    registrationDate: Date;

    /**
     * Rekisteröinnin loppupäivämäärä
     */
    endDate?: Date;

    /**
     * Yksi tarkoittaa kaupparekisteriä, kaksi säätiörekisteriä, kolme yhdistysrekisteriä, neljä Verohallintoa, viisi ennakkoperintärekisteriä, kuusi arvonlisäverovelvollisten rekisteriä, seitsemän työnantajarekisteriä ja kahdeksan vakuutusmaksuverovelvollisten rekisteriä
     */
    register: number;

    /**
     * Kaksikirjaiminen kielikoodi
     */
    language?: string;

    /**
     * Yksi tarkoittaa Verohallintoa, kaksi Patentti- ja rekisterihallitusta ja kolme väestörekisteriä
     */
    authority: number;

}
