/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Yritysten tiedot yritys- ja yhteisötietojärjestelmästä
 */
export interface BisCompany {
    /**
     * Y-tunnus
     */
    businessId: string;

    /**
     * Rekisteröintipäivämäärä
     */
    registrationDate: Date;

    /**
     * <a href=\"tr-company_v1.fi.txt\">Yritysmuoto</a>
     */
    companyForm?: string;

    /**
     * URI lisätietoja varten, jos ne eivät jo sisälly
     */
    detailsUri?: string;

    /**
     * Ensisijainen toiminimi
     */
    name: string;

}
