/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Yritysten tarkat tiedot yritys- ja yhteisötietojärjestelmästä
 */
export interface BisCompanyDetails {
    /**
     * Ensisijainen toiminimi ja käännökset
     */
    names: Array<models.BisCompanyName>;

    /**
     * Aputoiminimi ja käännökset
     */
    auxiliaryNames?: Array<models.BisCompanyName>;

    /**
     * Yrityksen käynti- ja postiosoitteet
     */
    addresses?: Array<models.BisAddress>;

    /**
     * Yritysmuoto ja käännökset
     */
    companyForms?: Array<models.BisCompanyForm>;

    /**
     * Tieto mahdollisesta konkurssi-, selvitystila- tai saneerausmenettelystä
     */
    liquidations?: Array<models.BisCompanyLiquidation>;

    /**
     * Yrityksen toimialat ja käännökset
     */
    businessLines?: Array<models.BisCompanyBusinessLine>;

    /**
     * Yrityksen kieli/kielet
     */
    languages?: Array<models.BisCompanyLanguage>;

    /**
     * Yrityksen kotipaikka ja sen käännökset
     */
    registeredOffices?: Array<models.BisCompanyRegisteredOffice>;

    /**
     * Yrityksen yhteystiedot ja käännökset
     */
    contactDetails?: Array<models.BisCompanyContactDetail>;

    /**
     * Yrityksen rekisterimerkinnät
     */
    registeredEntries?: Array<models.BisCompanyRegisteredEntry>;

    /**
     * Muutokset yrityksen Y-tunnukseen
     */
    businessIdChanges?: Array<models.BisCompanyBusinessIdChange>;

    /**
     * Y-tunnus
     */
    businessId: string;

    /**
     * Rekisteröintipäivämäärä
     */
    registrationDate: Date;

    /**
     * Yritysmuoto
     */
    companyForm?: string;

    /**
     * URI lisätietoja varten, jos ne eivät jo sisälly
     */
    detailsUri?: string;

    /**
     * Ensisijainen toiminimi
     */
    name: string;

}
