/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 
 */
export interface BisCompanyBusinessIdChange {
    /**
     * Nolla tarkoittaa yhteistä, yksi Patentti- ja rekisterihallitusta, kaksi Verohallintoa ja kolme yritys- ja yhteisötietojärjestelmää
     */
    source?: number;

    /**
     * Syyn kuvaus
     */
    description: string;

    /**
     * Syykoodi
     */
    reason: string;

    /**
     * Y-tunnuksen muutoksen päivämäärä
     */
    changeDate?: Date;

    /**
     * Yksi tarkoittaa ensisijaista toiminimeä, kaksi ensisijaisten toiminimien käännöksiä, kolme aputoiminimiä ja neljä aputoiminimien käännöksiä
     */
    change: number;

    /**
     * Vanha Y-tunnus
     */
    oldBusinessId: string;

    /**
     * Uusi Y-tunnus
     */
    newBusinessId: string;

    /**
     * Kaksikirjaiminen kielikoodi
     */
    language?: string;

}
